### ISSUE TITLE
代码调试时遇到了问题

### ISSUE THREAD

**Issue by luliang520** [Yixin-F/better_fastlio2#3]
*** 没有规则可制作目标“/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++fs.a”，由“/home/luliang/code/projectlw/ws_livox/devel/lib/fast_lio_sam/fastlio_sam_mapping” 需求。 停止。

**Comment by Syrinel167** [comment]
I met the same problem.
Because the last few lines of the CMakeList.txt file in better_fastlio2 hardcode the path to /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++fs.a, which does not exist in your environment, you can use the command `find / -name libstdc++fs.a` to search for it. The result will usually appear in a directory numbered 8 or 9.
Then you can resolve this issue by following these steps:
```
sudo mkdir -p /usr/lib/gcc/x86_64-linux-gnu/7/
sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++fs.a /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++fs.a
```
